"""
模型架构配置
定义每个模型的高层架构信息、层结构、描述等
"""

ARCHITECTURES = {
    "efficientnet_b0": {
        "name": "EfficientNet-B0",
        "type": "CNN",
        "description": "Google 2019年提出的高效卷积网络，使用复合缩放策略平衡深度、宽度和分辨率",
        "paper": "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks",
        "total_params": "5,288,548",
        "architecture": {
            "input": {"shape": "224×224×3", "description": "RGB 输入图像"},
            "layers": [
                {
                    "name": "ConvStem",
                    "type": "Conv2d + BN + Swish",
                    "channels": 32,
                    "kernel": "3×3",
                    "stride": 2,
                    "output_shape": "112×112×32",
                    "description": "初始卷积层，提取低级特征",
                },
                {
                    "name": "Block 0",
                    "type": "MBConv1 (×1)",
                    "channels": 16,
                    "kernel": "3×3",
                    "stride": 1,
                    "output_shape": "112×112×16",
                    "description": "浅层特征提取，保留空间细节",
                },
                {
                    "name": "Block 1",
                    "type": "MBConv6 (×2)",
                    "channels": 24,
                    "kernel": "3×3",
                    "stride": 2,
                    "output_shape": "56×56×24",
                    "description": "首次下采样，学习边缘和纹理特征",
                },
                {
                    "name": "Block 2",
                    "type": "MBConv6 (×2)",
                    "channels": 40,
                    "kernel": "5×5",
                    "stride": 2,
                    "output_shape": "28×28×40",
                    "description": "扩大感受野，捕捉更大范围的模式",
                },
                {
                    "name": "Block 3",
                    "type": "MBConv6 (×3)",
                    "channels": 80,
                    "kernel": "3×3",
                    "stride": 2,
                    "output_shape": "14×14×80",
                    "description": "深度特征学习，提取复杂语义信息",
                },
                {
                    "name": "Block 4",
                    "type": "MBConv6 (×3)",
                    "channels": 112,
                    "kernel": "5×5",
                    "stride": 1,
                    "output_shape": "14×14×112",
                    "description": "保持空间分辨率，增强特征表达",
                },
                {
                    "name": "Block 5",
                    "type": "MBConv6 (×4)",
                    "channels": 192,
                    "kernel": "5×5",
                    "stride": 2,
                    "output_shape": "7×7×192",
                    "description": "高层语义抽象，整合全局信息",
                },
                {
                    "name": "Block 6",
                    "type": "MBConv6 (×1)",
                    "channels": 320,
                    "kernel": "3×3",
                    "stride": 1,
                    "output_shape": "7×7×320",
                    "description": "最终特征融合，为分类做准备",
                },
                {
                    "name": "ConvHead",
                    "type": "Conv2d + BN + Swish",
                    "channels": 1280,
                    "kernel": "1×1",
                    "stride": 1,
                    "output_shape": "7×7×1280",
                    "description": "最终卷积层，融合特征",
                },
                {
                    "name": "GlobalPool",
                    "type": "AdaptiveAvgPool2d",
                    "channels": 1280,
                    "kernel": "-",
                    "stride": "-",
                    "output_shape": "1×1×1280",
                    "description": "全局平均池化",
                },
                {
                    "name": "Classifier",
                    "type": "Linear + Dropout",
                    "channels": 10,
                    "kernel": "-",
                    "stride": "-",
                    "output_shape": "10",
                    "description": "分类头，输出10个类别",
                },
            ],
        },
        "training_config": {
            "optimizer": "AdamW",
            "learning_rate": "1e-4",
            "batch_size": 32,
            "epochs": 30,
            "scheduler": "CosineAnnealingLR",
            "weight_decay": "0.01",
            "image_size": "224×224",
            "data_augmentation": [
                "RandomCrop",
                "RandomHorizontalFlip",
                "ColorJitter",
                "Normalize",
            ],
        },
    },
    "swin_tiny": {
        "name": "Swin Transformer Tiny",
        "type": "Transformer",
        "description": "Microsoft 2021年提出的视觉Transformer，使用移位窗口机制实现层级特征学习",
        "paper": "Swin Transformer: Hierarchical Vision Transformer using Shifted Windows",
        "total_params": "27,527,044",
        "architecture": {
            "input": {"shape": "224×224×3", "description": "RGB 输入图像"},
            "layers": [
                {
                    "name": "Patch Embed",
                    "type": "Conv2d 4×4",
                    "channels": 96,
                    "kernel": "4×4",
                    "stride": 4,
                    "output_shape": "56×56×96",
                    "description": "将图像分割为4×4的图像块并嵌入为96维向量",
                },
                {
                    "name": "Stage 1 (layers_0)",
                    "type": "Swin Transformer Block ×2",
                    "channels": 96,
                    "kernel": "7×7窗口",
                    "stride": 1,
                    "output_shape": "56×56×96",
                    "description": "窗口自注意力，保持空间分辨率",
                },
                {
                    "name": "Stage 2 (layers_1)",
                    "type": "Patch Merging + Swin Block ×2",
                    "channels": 192,
                    "kernel": "7×7窗口",
                    "stride": 2,
                    "output_shape": "28×28×192",
                    "description": "下采样+自注意力，空间减半通道翻倍",
                },
                {
                    "name": "Stage 3 (layers_2)",
                    "type": "Patch Merging + Swin Block ×6",
                    "channels": 384,
                    "kernel": "7×7窗口",
                    "stride": 2,
                    "output_shape": "14×14×384",
                    "description": "下采样+6层自注意力，提取更抽象特征",
                },
                {
                    "name": "Stage 4 (layers_3)",
                    "type": "Patch Merging + Swin Block ×2",
                    "channels": 768,
                    "kernel": "7×7窗口",
                    "stride": 2,
                    "output_shape": "7×7×768",
                    "description": "最终阶段，最高级语义特征",
                },
                {
                    "name": "Norm",
                    "type": "LayerNorm",
                    "channels": 768,
                    "kernel": "-",
                    "stride": "-",
                    "output_shape": "768",
                    "description": "层归一化",
                },
                {
                    "name": "Head",
                    "type": "Linear",
                    "channels": 10,
                    "kernel": "-",
                    "stride": "-",
                    "output_shape": "10",
                    "description": "分类头，输出10个类别",
                },
            ],
        },
        "training_config": {
            "optimizer": "AdamW",
            "learning_rate": "1e-4",
            "batch_size": 32,
            "epochs": 50,
            "scheduler": "CosineAnnealingLR",
            "weight_decay": "0.01",
            "image_size": "224×224",
            "data_augmentation": [
                "RandomCrop",
                "RandomHorizontalFlip",
                "ColorJitter",
                "Normalize",
            ],
        },
    },
    "swin_tiny_feature": {
        "name": "Swin Transformer Tiny (Feature Extractor)",
        "type": "Transformer (仅训练分类头)",
        "description": "使用预训练的 Swin Transformer 作为特征提取器，仅训练最后的分类头",
        "paper": "Swin Transformer: Hierarchical Vision Transformer using Shifted Windows",
        "total_params": "7,690 (可训练)",
        "architecture": {
            "input": {"shape": "224×224×3", "description": "RGB 输入图像"},
            "layers": [
                {
                    "name": "Patch Embed",
                    "type": "Conv2d 4×4 (冻结)",
                    "channels": 96,
                    "kernel": "4×4",
                    "stride": 4,
                    "output_shape": "56×56×96",
                    "description": "预训练权重，参数冻结",
                },
                {
                    "name": "Stage 1 (layers_0)",
                    "type": "Swin Blocks ×2 (冻结)",
                    "channels": 96,
                    "kernel": "7×7窗口",
                    "stride": 1,
                    "output_shape": "56×56×96",
                    "description": "预训练权重，提取低级特征",
                },
                {
                    "name": "Stage 2 (layers_1)",
                    "type": "Patch Merging + Swin Blocks (冻结)",
                    "channels": 192,
                    "kernel": "7×7窗口",
                    "stride": 2,
                    "output_shape": "28×28×192",
                    "description": "预训练权重，下采样+特征提取",
                },
                {
                    "name": "Stage 3 (layers_2)",
                    "type": "Patch Merging + Swin Blocks (冻结)",
                    "channels": 384,
                    "kernel": "7×7窗口",
                    "stride": 2,
                    "output_shape": "14×14×384",
                    "description": "预训练权重，提取中级特征",
                },
                {
                    "name": "Stage 4 (layers_3)",
                    "type": "Patch Merging + Swin Blocks (冻结)",
                    "channels": 768,
                    "kernel": "7×7窗口",
                    "stride": 2,
                    "output_shape": "7×7×768",
                    "description": "预训练权重，提取高级语义特征",
                },
                {
                    "name": "Norm",
                    "type": "LayerNorm (冻结)",
                    "channels": 768,
                    "kernel": "-",
                    "stride": "-",
                    "output_shape": "768",
                    "description": "层归一化，参数冻结",
                },
                {
                    "name": "Head",
                    "type": "Linear (可训练)",
                    "channels": 10,
                    "kernel": "-",
                    "stride": "-",
                    "output_shape": "10",
                    "description": "唯一可训练的分类头，7,690个参数",
                },
            ],
        },
        "training_config": {
            "optimizer": "AdamW",
            "learning_rate": "1e-4",
            "batch_size": 32,
            "epochs": 30,
            "scheduler": "CosineAnnealingLR",
            "weight_decay": "0.01",
            "image_size": "224×224",
            "data_augmentation": [
                "RandomCrop",
                "RandomHorizontalFlip",
                "ColorJitter",
                "Normalize",
            ],
            "note": "仅训练分类头，基础模型参数冻结",
        },
    },
}
